### ISSUE TITLE
pre-commit gha error

### ISSUE THREAD

**Issue by magnusviri** [univ-of-utah-marriott-library-apple/jctl#56]
@homebysix it looks like the pre-commit stuff isn't working anymore. I'm tagging you because I believe you are using it in other projects. If you fixed it in any other projects or know anything about the error, could you let me know and give me some hints? I'm still unfamiliar with the code so I'm not sure how to get the action to work again. Here's the log.

https://github.com/univ-of-utah-marriott-library-apple/jctl/actions/runs/3906886411/jobs/6675527573#step:4:45

**Comment by homebysix** [comment]
I think the fix will be to change [gitlab.com](http://gitlab.com/) to [github.com](http://github.com/) on [this line](https://github.com/univ-of-utah-marriott-library-apple/jctl/blob/main/.pre-commit-config.yaml#L20). Then run pre-commit autoupdate to get the new revisions.

[Here's](https://github.com/autopkg/autopkg/commit/3491df2ff446084fcb0bb6e50d20fe1aad3ff66a) an example of what that change might look like.

Root cause: pycqa changed where its repo is hosted.

**Comment by magnusviri** [comment]
Thank you! That fixed it!
